import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Header } from "@/components/header";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={font.className}>
          <div className="sticky top-0 z-50 bg-white dark:bg-neutral-900 shadow-sm dark:shadow-gray-800 px-10">
            <Header />
          </div>
          <main className="flex justify-center w-full">
            {children}
          </main>
        </body>
      </html>
    </SessionProvider>
  );
}
